/** @type { import('prettier').Config} */
module.exports = {
  endOfLine: 'lf',
  semi: false,
  singleQuote: true,
  tabWidth: 2,
  trailingComma: 'es5',
  importOrder: [
    '^(react/(.*)$|^react$)',
    '^(next/(.*)$|^next$)',
    '<THIRD_PARTY_MODULES>',
    '',
    '^types$',
    '',
    '^@/styles/(.*)$',
    '',
    '^@/lib/utils/(.*)$',
    '^@/lib/types/(.*)$',
    '',
    '^@/lib/contexts/(.*)$',
    '^@/lib/hooks/(.*)$',
    '',
    '^@/lib/(.*)$',
    '',
    '^@/components/ui/(.*)$',
    '',
    '^@/components/(.*)$',
    '',
    '^@/app/(.*)$',
    '',
    '^[./]',
  ],
  importOrderSeparation: true,
  importOrderSortSpecifiers: true,
  importOrderBultinModulesToTop: true,
  importOrderParserPlugins: ['typescript', 'jsx', 'decorators-legacy'],
  importOrderMergeDublicateImports: true,
  importOrderCombineTypeAndValueImports: true,
  plugins: ['@ianvs/prettier-plugin-sort-imports'],
}
